version: "3.8"

services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "car_for_sale"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      ConnectionStrings__Default: "Server=db;Database=car_for_sale;User Id=postgres;Password=123456"
      ASPNETCORE_HTTP_PORTS: "8080"
    ports:
      - "5000:80"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  pgdata:
    driver: local
